sudo: required
language: bash
env:
  global:
    - LIVE_SERVICE=docker-react-test-service
    - LIVE_CLUSTER_NAME=docker-react-test
    - LIVE_APP_NAME=docker-react-test
    - AWS_URL=523775743690.dkr.ecr.us-west-2.amazonaws.com

services:
  - docker

before_install:
  - chmod +x docker-deploy/docker_push.sh
  - chmod +x docker-deploy/ecs.sh
  - chmod +x docker-deploy/ecs_deploy.sh
  - docker build -t kevinluoamzn/docker-react-test -f Dockerfile.dev .

jobs:
  include:
    - stage: tests
      script: 
        - docker run -e CI=true kevinluoamzn/docker-react-test npm run test -- --coverage
    - stage: deploy
      script:
        - docker-deploy/docker_push.sh
        - docker-deploy/ecs_deploy.sh