sudo: required
language: bash
env:
  global:
    - LIVE_SERVICE=docker-react-test-service
    - LIVE_CLUSTER_NAME=docker-react-test
    - LIVE_APP_NAME=docker-react-test
    - AWS_URL=523775743690.dkr.ecr.us-west-2.amazonaws.com

services:
  - docker

before_install:
  - docker build -t kevinluoamzn/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true kevinluoamzn/docker-react-test npm run test -- --coverage

after_success:
  - docker-deploy/docker_push.sh
  - docker-deploy/ecs_deploy.sh