sudo: required
services:
  - docker

before_install:
  - docker build -t kevinluoamzn/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true kevinluoamzn/docker-react-test npm run test -- --coverage