sudo: required
dist: xenial
language: bash
python:
  - "3.6"
env:
  global:
    - LIVE_SERVICE=docker-react-test-service
    - LIVE_CLUSTER_NAME=docker-react-test
    - LIVE_APP_NAME=docker-react-test
    - AWS_URL=523775743690.dkr.ecr.us-west-2.amazonaws.com

services:
  - docker

before_install:
  - chmod +x docker-deploy/docker_push.sh
  - chmod +x docker-deploy/ecs.sh
  - chmod +x docker-deploy/ecs_deploy.sh

jobs:
  include:
    # - stage: tests
    #   script: 
    #     - docker build -t kevinluoamzn/docker-react-test -f Dockerfile.dev .
    #     - docker run -e CI=true kevinluoamzn/docker-react-test npm run test -- --coverage
    - stage: deploy
      before_script:
        - docker-deploy/docker_push.sh
      script:
        - docker-deploy/ecs_deploy.sh